### PR TITLE
🐝 Tweaked pressing honey a bit

### PR DESCRIPTION
**Pull request by DoctorVanGogh**
Something simpler 😁 

- Pressed honey mash is now non perishable (neither honey nor beeswax is perishable, why should a mash of both be)
- Pressing honey in the screw press now gives as good as (if not sliiiiiightly) better results than doing it by hand. 
  
  | Operation | Honeycomb | Honey | Beeswax |
  |---|---:|---:|---:|
  |  Manual | 50 | 10L  | 50 |
  |  Press <br/> (_before_) | 49 | 10L  | 40 |
  |  Press <br/> (**now**) | 49 | 10L  | 50 |

- Pressed honey comb can no longer be "fed" to animals. Updated the description and added a Harmony patch to block adding the mash to the trough. 
Tried doing this via pure json, just would not work. Could either build a solution of "can still stick wax into a tub but it wont do anything" or "cant stick wax in a tub, but this will break compatibility with any mod that adds extra fruits".
Doing this via harmony just filters out the honey mash.

### CODE REVIEW

**Comment by DoctorVanGogh** [comment]
This one needs a follow up... I made all mashes non perishable :(

**Comment by l33tmaan** [comment]
Do you mean this line from the pressed mash patch?

`"game:pressedmash-*": null`

**Comment by DoctorVanGogh** [comment]
Yes, but also no

Because I move the default perishability out of the way, stick in a branch for honey or "others" and then put the default back into the "other" branch.
https://github.com/l33tmaan/EFRecipes/blob/467f9784bed0080c099274a0aaa10cd72477d45d/EFRecipes/assets/expandedfoods/patches/pressedmash.json#L135-L158

I'll need to watch the document mutation with a debugger. Oh well - people can enjoy their non perishing mashes for a few days if they play with the github version 😀

**Comment by DoctorVanGogh** [comment]
Okay... today I learned: The game does not like domains in its' `...byType` definitions...

**Pull request merged**
